/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ATHistoryPanel.java
 *
 * Created on Nov 15, 2012, 3:37:42 PM
 */

package JavaTron;

import javax.swing.JEditorPane;

/**
 *
 * @author root
 */
public class ATHistoryPanel extends javax.swing.JPanel {
	AudioTronState at;
    /** Creates new form ATHistoryPanel */
    public ATHistoryPanel(AudioTronState at_) {
        initComponents();
		at=at_;
		jWebText.setText("Press 'Refresh' to get History.");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRefreshButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jWebText = new javax.swing.JEditorPane();

        jRefreshButton.setText("Refresh");
        jRefreshButton.setName("jRefreshButton"); // NOI18N
        jRefreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRefreshButtonActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jWebText.setContentType("text/html"); // NOI18N
        jWebText.setName("jWebText"); // NOI18N
        jScrollPane2.setViewportView(jWebText);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jRefreshButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRefreshButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

	private void jRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshButtonActionPerformed

		jWebText.setText("Retrieving Data...");
		doGet d=new doGet();
		d.start();
	}//GEN-LAST:event_jRefreshButtonActionPerformed

	private class doGet extends Thread{

		public void run(){
			StringBuffer output=new StringBuffer();
			JTP.HtmlParser parser=new JTP.HtmlParser(output);
			at.getPage("/history.asp",null,parser);
			while(!output.toString().endsWith("</html>")){}
			jWebText.setText(output.toString());
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jRefreshButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JEditorPane jWebText;
    // End of variables declaration//GEN-END:variables

}
