/*
 * ATNetFileConfigPanel.java
 *
 * Created on Mar 25, 2010, 2:27:28 PM
 */

package JavaTron;

//import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Joe Culbreth
 */
public class ATNetFileConfigPanel extends javax.swing.JPanel {
	AudioTronState at;
    /** Creates new form ATNetFileConfigPanel */
    public ATNetFileConfigPanel(AudioTronState at_) {
        at=at_;
		initComponents();
		winUserText.setText(Configuration.getProperty(Configuration.KEY_WIN_USERNAME));
		winPassText.setText(JTP.decrypt(Configuration.getProperty(Configuration.KEY_WIN_PASSWORD)));
		if(Configuration.getProperty(Configuration.KEY_WIN_98PASSWORD)!=null){
			String p = JTP.decrypt(Configuration.getProperty(Configuration.KEY_WIN_98PASSWORD));
			//System.out.println("98Password: " + p);
			win98PassText.setText(p);
		}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        jCheckRadioFileButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        win98PassText = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        win98Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        winUserText = new javax.swing.JTextField();
        winPassText = new javax.swing.JPasswordField();
        setButton = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Check for New Files"));
        jPanel1.setName("jPanel1"); // NOI18N

        searchButton.setText("Songs");
        searchButton.setToolTipText("Tell the Audiotron to 'search' for new files. This is a LONG operation!");
        searchButton.setName("searchButton"); // NOI18N
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        jCheckRadioFileButton.setText("Radio");
        jCheckRadioFileButton.setToolTipText("tells the audiotron to rescan the radio.txt file"); // NOI18N
        jCheckRadioFileButton.setName("jCheckRadioFileButton"); // NOI18N
        jCheckRadioFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckRadioFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckRadioFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jCheckRadioFileButton, searchButton});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(jCheckRadioFileButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Win 95/98/ME Password"));
        jPanel2.setName("jPanel2"); // NOI18N

        win98PassText.setName("win98PassText"); // NOI18N
        win98PassText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                win98PassTextActionPerformed(evt);
            }
        });

        jLabel3.setText("Pass");
        jLabel3.setName("jLabel3"); // NOI18N

        win98Button.setText("Set");
        win98Button.setName("win98Button"); // NOI18N
        win98Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                win98ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(win98PassText, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addComponent(win98Button, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(win98PassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(win98Button))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Win2K/XP Authorization"));
        jPanel3.setName("jPanel3"); // NOI18N

        jLabel1.setText("User");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Pass");
        jLabel2.setName("jLabel2"); // NOI18N

        winUserText.setName("winUserText"); // NOI18N
        winUserText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                winUserTextFocusLost(evt);
            }
        });
        winUserText.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                winUserTextInputMethodTextChanged(evt);
            }
        });

        winPassText.setName("winPassText"); // NOI18N
        winPassText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                winPassTextFocusLost(evt);
            }
        });

        setButton.setText("Set");
        setButton.setName("setButton"); // NOI18N
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(winUserText, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(winPassText, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                    .addComponent(setButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(winUserText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(winPassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void win98PassTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_win98PassTextActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_win98PassTextActionPerformed

	private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
		at.search();
	}//GEN-LAST:event_searchButtonActionPerformed

	private void winUserTextInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_winUserTextInputMethodTextChanged
		System.out.println("Change : "+winUserText.getText());
	}//GEN-LAST:event_winUserTextInputMethodTextChanged

	private void winUserTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_winUserTextFocusLost
		Configuration.setProperty(Configuration.KEY_WIN_USERNAME, winUserText.getText());
	}//GEN-LAST:event_winUserTextFocusLost

	private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed

		boolean doit=true;
		if(!winUserText.getText().equals("") ){
			if(winPassText.getPassword().length < 1 ){
				int save=JOptionPane.showConfirmDialog(this,
												"This will set your password to an empty password\r\n        Continue?",
												"Empty Password",
												JOptionPane.YES_NO_OPTION);
				if(save != JOptionPane.YES_OPTION)
					doit=false;
			}

			if(doit){
				int sure = JOptionPane.showConfirmDialog(this,
														"This will change the password and username your Audiotron uses to access its music files! \r\nAre you SURE!",
														"Confirm Authentication Change",
														JOptionPane.YES_NO_OPTION);
				if(sure==JOptionPane.YES_OPTION){
					System.out.println("Setting "+winUserText.getText()+":"+new String(winPassText.getPassword()) );/*DoPost*/
					String u=new String(winUserText.getText());
					String p=new String(winPassText.getPassword());
					String encryptedPassword=JTP.encrypt(p);
					String decryptedPassword=JTP.decrypt(encryptedPassword);
					System.out.println("Encrypt: " + JTP.encrypt(p));
					System.out.println("Plain: "+ decryptedPassword);
					Configuration.setProperty(Configuration.KEY_WIN_PASSWORD, encryptedPassword);
					Configuration.saveProperties();
					//TODO Do the dirty deed here
					at.setXPAuth(u, decryptedPassword);

					JOptionPane.showMessageDialog(this,"Network Password Changed",
													"Password Changed",JOptionPane.WARNING_MESSAGE);
				}
			}
		}

	}//GEN-LAST:event_setButtonActionPerformed

	private void saveWinPassword(){
		String p=new String(winPassText.getPassword());
		String encryptedPassword=JTP.encrypt(p);
		String decryptedPassword=JTP.decrypt(encryptedPassword);
		System.out.println("Encrypt: " + JTP.encrypt(p));
		System.out.println("Plain: "+ decryptedPassword);
		Configuration.setProperty(Configuration.KEY_WIN_PASSWORD, encryptedPassword);
		Configuration.saveProperties();
	}

	private void win98ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_win98ButtonActionPerformed
		int sure=JOptionPane.ABORT;
		String decryptedPassword=new String();
		if(win98PassText.getPassword().length > 0 ){
			sure = JOptionPane.showConfirmDialog(this,
													"This will change the password your Audiotron uses to access its music files! \r\nAre you SURE!",
													"Confirm Authentication Change",
													JOptionPane.YES_NO_OPTION);
			System.out.println("Setting win98:" + new String(win98PassText.getPassword()) );
			String p = new String(win98PassText.getPassword());
			String encryptedPassword=JTP.encrypt(p);
			decryptedPassword=JTP.decrypt(encryptedPassword);
			System.out.println("Encrypt98: " + JTP.encrypt(p));
			System.out.println("Plain98: "+ decryptedPassword);
			Configuration.setProperty(Configuration.KEY_WIN_98PASSWORD, encryptedPassword);
			Configuration.saveProperties();
			
		}
		if(win98PassText.getPassword().length < 1){
			sure = JOptionPane.showConfirmDialog(this,
													"This will clear out the password your Audiotron uses to access its music files! \r\nAre you SURE!",
													"Empty Password",
													JOptionPane.YES_NO_OPTION);
			System.out.println("Setting win98:" + new String(win98PassText.getPassword()) );
		}

		if(sure == JOptionPane.YES_OPTION){
				//TODO Do the dirty deed here
				at.setWin98Auth(decryptedPassword);
				JOptionPane.showMessageDialog(this,"Win98 Network Password Changed",
										"Password Changed", JOptionPane.WARNING_MESSAGE);
		}
		
	}//GEN-LAST:event_win98ButtonActionPerformed

	private void winPassTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_winPassTextFocusLost
		saveWinPassword();
	}//GEN-LAST:event_winPassTextFocusLost

	private void jCheckRadioFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckRadioFileButtonActionPerformed
		at.checkRadioText();
	}//GEN-LAST:event_jCheckRadioFileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCheckRadioFileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton setButton;
    private javax.swing.JButton win98Button;
    private javax.swing.JPasswordField win98PassText;
    private javax.swing.JPasswordField winPassText;
    private javax.swing.JTextField winUserText;
    // End of variables declaration//GEN-END:variables

}
