/*
 * ATNetConfigPanel.java
 * Copyright (C) 2010 Joe Culbreth
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 *
 *
 * Created on Mar 21, 2010, 4:34:27 PM
 */

package JavaTron;

//import javax.swing.event.*;
/**
 * A Network Configuration Panel
 * @author Joe Culbreth
 */
public class ATNetConfigPanel extends javax.swing.JPanel {
	AudioTronState at;
	MyUIHandler uiHandler;
    /** Creates new form ATNetConfigPanel */
    public ATNetConfigPanel(AudioTronState at_) {
        initComponents();
		at=at_;
		netAddressText.setText(at.getServer());
		netMaskText.setText("255.255.255.0");
		netDnsText.setText("192.168.30.2");
		netGatewayText.setText("192.168.30.1");

//		DocumentListener action = new DocumentListener() {
//			public void changedUpdate(DocumentEvent e) { uiHandler.netMask(); }
//			public void insertUpdate(DocumentEvent e) { uiHandler.netMask(); }
//			public void removeUpdate(DocumentEvent e) { uiHandler.netMask(); }
//		};
//		netMaskText.getDocument().addDocumentListener(action);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        setButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        useStaticRadio = new javax.swing.JRadioButton();
        useDhcpRadio = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        netAddressText = new javax.swing.JTextField();
        netMaskText = new javax.swing.JTextField();
        netGatewayText = new javax.swing.JTextField();
        netDnsText = new javax.swing.JTextField();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setName("jPanel3"); // NOI18N

        setButton.setText("Set");
        setButton.setName("setButton"); // NOI18N
        setButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addComponent(setButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(cancelButton)
                .addComponent(setButton))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Address Type"));
        jPanel1.setName("jPanel1"); // NOI18N

        buttonGroup1.add(useStaticRadio);
        useStaticRadio.setSelected(true);
        useStaticRadio.setText("Use Static IP");
        useStaticRadio.setName("useStaticRadio"); // NOI18N
        useStaticRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useStaticRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(useDhcpRadio);
        useDhcpRadio.setText("Use DHCP");
        useDhcpRadio.setName("useDhcpRadio"); // NOI18N
        useDhcpRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useDhcpRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(useStaticRadio)
                .addGap(18, 18, 18)
                .addComponent(useDhcpRadio)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(useStaticRadio)
                .addComponent(useDhcpRadio))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Static Address"));
        jPanel2.setName("jPanel2"); // NOI18N

        jLabel1.setText("IP Address");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("Mask");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel4.setText("Gateway");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel3.setText("DNS");
        jLabel3.setName("jLabel3"); // NOI18N

        netAddressText.setToolTipText("The Address you want your Audiotron to use");
        netAddressText.setName("netAddressText"); // NOI18N

        netMaskText.setToolTipText("IP Subnet mask, i.e. 255.255.255.0");
        netMaskText.setName("netMaskText"); // NOI18N

        netGatewayText.setToolTipText("Your Gateway's IP Address");
        netGatewayText.setName("netGatewayText"); // NOI18N

        netDnsText.setName("netDnsText"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(netDnsText)
                    .addComponent(netGatewayText)
                    .addComponent(netMaskText)
                    .addComponent(netAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(netAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netMaskText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netGatewayText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netDnsText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void setButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setButtonActionPerformed
		JPop j=new JPop("Oops!", "Feature Not Implemented...yet");
		if(dhcp){

		}else{
			String addr=netAddressText.getText();
			String mask=netMaskText.getText();
			String gateway=netGatewayText.getText();
			String dns=netDnsText.getText();
			// TODO set and issue POST command
		}


}//GEN-LAST:event_setButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		//setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed

	private void useStaticRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useStaticRadioActionPerformed
		netAddressText.setEnabled(true);
		netMaskText.setEnabled(true);
		netGatewayText.setEnabled(true);
		netDnsText.setEnabled(true);
		dhcp=false;
	}//GEN-LAST:event_useStaticRadioActionPerformed

	private void useDhcpRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useDhcpRadioActionPerformed
		netAddressText.setEnabled(false);
		netMaskText.setEnabled(false);
		netGatewayText.setEnabled(false);
		netDnsText.setEnabled(false);
		dhcp=true;
}//GEN-LAST:event_useDhcpRadioActionPerformed


protected class MyUIHandler extends GUIUtilities.UIHandler
    {
      public void netAddress()
      {
        Configuration.setProperty(Configuration.KEY_SERVER, netAddressText.getText());
      }
      public void netMask()
      {
        Configuration.setProperty(Configuration.KEY_NET_MASK, netMaskText.getText());
      }
      public void netGateway()
      {
		Configuration.setProperty(Configuration.KEY_NET_GATEWAY,netGatewayText.getText());
      }
	  public void netDns(){
		  Configuration.setProperty(Configuration.KEY_NET_DNS, netDnsText.getText());
	  }
	  public void netDhcp(){
		  Configuration.setBoolProperty(Configuration.KEY_NET_DHCP, dhcp);
	  }
    } // NetConfigPanel.MyUIHandler

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField netAddressText;
    private javax.swing.JTextField netDnsText;
    private javax.swing.JTextField netGatewayText;
    private javax.swing.JTextField netMaskText;
    private javax.swing.JButton setButton;
    private javax.swing.JRadioButton useDhcpRadio;
    private javax.swing.JRadioButton useStaticRadio;
    // End of variables declaration//GEN-END:variables
	private boolean dhcp=false;
}
