/*
 * ATRadioPanel.java
 *
 * Created on Mar 22, 2010, 12:44:15 AM
 */

package JavaTron;

import javax.swing.*;
/**
 * Panel to configure radio.txt retrieval/installation information
 *
 * @author Joe Culbreth
 */
public class ATRadioPanel extends javax.swing.JPanel {
	AudioTronState at;
    /** Creates new form ATRadioPanel */
    public ATRadioPanel(AudioTronState at_) {
        initComponents();
		at=at_;
		tbRadioIDText.setText(Configuration.getProperty(Configuration.KEY_RADIO_USERNAME));
		usernameText.setText(Configuration.getProperty(Configuration.KEY_NET_USERNAME));
		String password = new String(JTP.decrypt(Configuration.getProperty(Configuration.KEY_NET_PASSWORD)));
		passwordText.setText(password);
		
		hostText.setText(Configuration.getProperty(Configuration.KEY_RADIO_HOST));
		shareText.setText(Configuration.getProperty(Configuration.KEY_RADIO_SHARE));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getRadioButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hostText = new javax.swing.JTextField();
        shareText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        tbRadioIDText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        inputText = new javax.swing.JLabel();
        rptLabel = new javax.swing.JLabel();
        newRadioButton = new javax.swing.JButton();
        jRadioUpdateButton = new javax.swing.JButton();

        getRadioButton.setText("Get RadioList");
        getRadioButton.setName("getRadioButton"); // NOI18N
        getRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getRadioButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Net Username");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("Password");
        jLabel3.setName("jLabel3"); // NOI18N

        usernameText.setName("usernameText"); // NOI18N
        usernameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTextFocusLost(evt);
            }
        });

        jLabel4.setText("Host");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText("Share");
        jLabel5.setName("jLabel5"); // NOI18N

        hostText.setText("media");
        hostText.setName("hostText"); // NOI18N
        hostText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                hostTextFocusLost(evt);
            }
        });

        shareText.setText("media/music");
        shareText.setName("shareText"); // NOI18N
        shareText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                shareTextFocusLost(evt);
            }
        });

        passwordText.setName("passwordText"); // NOI18N
        passwordText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTextFocusLost(evt);
            }
        });

        jLabel6.setText("TBRadio ID");
        jLabel6.setName("jLabel6"); // NOI18N

        tbRadioIDText.setText("JOLLYROGER");
        tbRadioIDText.setName("tbRadioIDText"); // NOI18N
        tbRadioIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tbRadioIDTextFocusLost(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("URL"));
        jPanel1.setName("jPanel1"); // NOI18N

        inputText.setText("smb://");
        inputText.setToolTipText("This needs to be accessible from the device Javatron is running on");
        inputText.setName("inputText"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inputText, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inputText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rptLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rptLabel.setName("rptLabel"); // NOI18N

        newRadioButton.setText("Create New");
        newRadioButton.setName("newRadioButton"); // NOI18N
        newRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRadioButtonActionPerformed(evt);
            }
        });

        jRadioUpdateButton.setText("Rescan");
        jRadioUpdateButton.setToolTipText("Tells the audiotron to rescan  the Radio File"); // NOI18N
        jRadioUpdateButton.setName("jRadioUpdateButton"); // NOI18N
        jRadioUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(shareText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(hostText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(usernameText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(tbRadioIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jRadioUpdateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getRadioButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tbRadioIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hostText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(shareText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getRadioButton)
                    .addComponent(newRadioButton)
                    .addComponent(jRadioUpdateButton))
                .addGap(7, 7, 7)
                .addComponent(rptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void getRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getRadioButtonActionPerformed
		final String username=usernameText.getText();
		final String password =
				new String(JTP.decrypt(Configuration.getProperty(Configuration.KEY_NET_PASSWORD)));
		//System.out.println("Password: "+password);
		final String host=hostText.getText();
		final String share=shareText.getText();
		final String tbuser=tbRadioIDText.getText();

		String istring = "smb://"+host+"/"+share+"/radio.txt";
		inputText.setText(istring);
		final String radioURL=istring;

		/**
		 * Spawns the UI window for the radio editor
		 */
		class RadioThread extends Thread{
			public void run(){
				try{
					ATRadioFile rf = new ATRadioFile(host,share,username,password,"radio.txt");
					rptLabel.setText(" "+rf.getLastError());
					rf.setUsername(tbuser);
					rptLabel.setText(" "+rf.getLastError());
					ATRadioEditorDlg red=new ATRadioEditorDlg(at,JavaTron.getApplication().getUI().getFrame(),
																"Audiotron Radio List Editor",new JToggleButton(),
																rf.getStationList());
					System.out.println("arp.radioURL : "+ radioURL);
					red.setRadioURL(radioURL);
					red.setVisible(true);
					//rptLabel.setText(" Done...");
				}catch(Exception e){
					ATRadioEditorDlg red=new ATRadioEditorDlg(at,JavaTron.getApplication().getUI().getFrame(),
																"Audiotron Radio List Editor",new JToggleButton()
																);
					red.setVisible(true);
					//jLabel1.setText(e.getMessage());
					e.printStackTrace();
				}

			}
		}

		RadioThread r=new RadioThread();
		r.start();
		rptLabel.setText(" Fetching....");
	}//GEN-LAST:event_getRadioButtonActionPerformed

	private void tbRadioIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbRadioIDTextFocusLost
		Configuration.setProperty(Configuration.KEY_RADIO_USERNAME, tbRadioIDText.getText());
	}//GEN-LAST:event_tbRadioIDTextFocusLost

	private void usernameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTextFocusLost
		Configuration.setProperty(Configuration.KEY_NET_USERNAME, usernameText.getText());
	}//GEN-LAST:event_usernameTextFocusLost

	private void passwordTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTextFocusLost
		String p = new String(passwordText.getPassword());
		p=JTP.encrypt(p);
		Configuration.setProperty(Configuration.KEY_NET_PASSWORD, p);
	}//GEN-LAST:event_passwordTextFocusLost

	private void hostTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_hostTextFocusLost
		Configuration.setProperty(Configuration.KEY_RADIO_HOST, hostText.getText());
	}//GEN-LAST:event_hostTextFocusLost

	private void shareTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_shareTextFocusLost
		Configuration.setProperty(Configuration.KEY_RADIO_SHARE, shareText.getText());
	}//GEN-LAST:event_shareTextFocusLost

	private void newRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRadioButtonActionPerformed
		ATRadioEditorDlg red=new ATRadioEditorDlg(at,JavaTron.getApplication().getUI().getFrame(),
													"Radio Editor",new JToggleButton()
													);
		
		red.setVisible(true);
	}//GEN-LAST:event_newRadioButtonActionPerformed

	private void jRadioUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioUpdateButtonActionPerformed
		at.checkRadioText();
	}//GEN-LAST:event_jRadioUpdateButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getRadioButton;
    private javax.swing.JTextField hostText;
    private javax.swing.JLabel inputText;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRadioUpdateButton;
    private javax.swing.JButton newRadioButton;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel rptLabel;
    private javax.swing.JTextField shareText;
    private javax.swing.JTextField tbRadioIDText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables

}
