/*
 * ATWebDisplayDlg.java
 *
 * Created on Feb 23, 2010, 3:40:28 PM
 */

package JavaTron;

import java.io.*;
import java.net.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.text.html.*;
import javax.swing.event.*;

/**
 * Displays the Audiotron Web pages (used for development)
 * @author Joe Culbeth <joe@connexsmart.com>
 * @version $Revision: 1.3 $
 */
public class ATWebDisplayDlg extends GUIUtilities.DockedDialog implements HyperlinkListener{

	AudioTronState at;
	HtmlParser parser;
	StringBuffer doc;
	String host;
    /** Creates new form ATWebDisplayDlg */
    public ATWebDisplayDlg( AudioTronState at_,
							java.awt.Frame parent,
							String label_,
							JToggleButton toggle) {
        super(parent, label_, toggle);
		at=at_;
        initComponents();
		host=at.getServer();
    }

	public ATWebDisplayDlg( AudioTronState at_,
							java.awt.Frame parent,
							String label_,
							JToggleButton toggle,
							String webDoc)
	{
		super(parent, label_, toggle);
		at=at_;
		initComponents();
		webContentPane.addHyperlinkListener(this);
		webContentPane.setText(webDoc);
		host=at.getServer();
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Home = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        shareButton = new javax.swing.JButton();
        filesButton = new javax.swing.JButton();
        webButton = new javax.swing.JButton();
        networkButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        webContentPane = new javax.swing.JEditorPane();
        checkFilesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Home.setText("Home");
        Home.setName("Home"); // NOI18N
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        historyButton.setText("History");
        historyButton.setName("historyButton"); // NOI18N
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });

        shareButton.setText("Shares");
        shareButton.setName("shareButton"); // NOI18N
        shareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareButtonActionPerformed(evt);
            }
        });

        filesButton.setText("File Setting");
        filesButton.setName("filesButton"); // NOI18N
        filesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filesButtonActionPerformed(evt);
            }
        });

        webButton.setText("Web Settings");
        webButton.setName("webButton"); // NOI18N
        webButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButtonActionPerformed(evt);
            }
        });

        networkButton.setText("Network");
        networkButton.setName("networkButton"); // NOI18N
        networkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        webContentPane.setContentType("text/html"); // NOI18N
        webContentPane.setName("webContentPane"); // NOI18N
        jScrollPane1.setViewportView(webContentPane);

        checkFilesButton.setText("Check");
        checkFilesButton.setName("checkFilesButton"); // NOI18N
        checkFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkFilesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Home)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(historyButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(shareButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(webButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(networkButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkFilesButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home)
                    .addComponent(historyButton)
                    .addComponent(shareButton)
                    .addComponent(filesButton)
                    .addComponent(webButton)
                    .addComponent(networkButton)
                    .addComponent(checkFilesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
		getInfo("/index.asp");
//		try{
//
//			webContentPane.setPage("http://"+host+"/index.asp");
//		}catch(IOException e){
//			e.printStackTrace();
//		}
		
	}//GEN-LAST:event_HomeActionPerformed

	private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
		getInfo("/history.asp");
//		try{
//			webContentPane.setPage("http://"+host+"/history.asp");
//		}catch(IOException e){
//			e.printStackTrace();
//		}
	}//GEN-LAST:event_historyButtonActionPerformed

	private void shareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareButtonActionPerformed
		getInfo("/shares.asp");
//		try{
//			webContentPane.setPage("http://"+host+"/shares.asp");
//		}catch(IOException e){
//			e.printStackTrace();
//		}
	}//GEN-LAST:event_shareButtonActionPerformed

	private void filesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filesButtonActionPerformed
		getInfo("/filecfg.asp");
//		try{
//			webContentPane.setPage("http://"+host+"/filecfg.asp");
//		}catch(IOException e){
//			e.printStackTrace();
//		}
	}//GEN-LAST:event_filesButtonActionPerformed

	private void webButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButtonActionPerformed
		getInfo("/webcfg.asp");
//		try{
//			String address="http://"+host+"/webcfg.asp";
//			webContentPane.setPage("http://"+host+"/webcfg.asp");
//		}catch(IOException e){
//			e.printStackTrace();
//		}
	}//GEN-LAST:event_webButtonActionPerformed

	private void networkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkButtonActionPerformed
		getInfo("/network.asp");
//		try{
//			webContentPane.setPage("http://"+host+"/network.asp");
//		}catch(IOException e){
//			e.printStackTrace();
//		}
	}//GEN-LAST:event_networkButtonActionPerformed

	private void checkFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkFilesButtonActionPerformed
		getInfo("/chkfiles.asp");
		//		try{
//			webContentPane.setPage("http://"+host+"/chkfiles.asp");
//		}catch(IOException e){
//			e.printStackTrace();
//		}
	}//GEN-LAST:event_checkFilesButtonActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                ATWebDisplayDlg dialog = new ATWebDisplayDlg(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
	public void setContents(String doc){
		webContentPane.setText(doc);

	}

	public void getInfo(String address){
		parser=new HtmlParser(doc=new StringBuffer());
		at.getPage(address, null, parser);
		//this.setContents(doc.toString());
	}


	private void doPost(){
		return;
	}

	public void hyperlinkUpdate(HyperlinkEvent event) {
		JOptionPane.showMessageDialog(null, "Feature Not Implemented");
		if (event.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
			try {
				JOptionPane.showMessageDialog(null, "Feature Not Implemented");
				webContentPane.setPage(event.getURL());
			} catch(IOException ioe) {
				// Some warning to user
			}
		}
	}


	private class HtmlParser extends JTP.HtmlParser{
		StringBuffer info;
		public HtmlParser(StringBuffer info_){
			super(info_);
			info=info_;
		}

		public void end(boolean error){
			ATWebDisplayDlg.this.setContents(info.toString());

		}

		public boolean parse(String content){
			content=content.replace("size=\"3\"","size=\"4\"");
			content=content.replace("size=\"2\"","size=\"3\"");
			return super.parse(content);
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton checkFilesButton;
    private javax.swing.JButton filesButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton networkButton;
    private javax.swing.JButton shareButton;
    private javax.swing.JButton webButton;
    private javax.swing.JEditorPane webContentPane;
    // End of variables declaration//GEN-END:variables

}
